version: "3.4"

services:
  db:
    container_name: my_db
    image: postgres:10
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      - POSTGRES_PASSWORD = pass
      - POSTGRES_USER = springdb
      - POSTGRES_DB = springdb
    deploy:
      placement:
        constraints: [node.role == manager]

  rest-app:
    image: rest-app
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  db-data: